# only meta info here, nothing about the individual steps

base = "test.toml"

[train]
command = """python3 -c 'print(__import__("os").environ["foo"])'"""
venv = "venv"  # path to some virtualenv

[train.environment]
# this will cause execution to be called with python3 my_model.py train --foo=bar
foo = "bar"

[eval]
command = "echo hiii"
venv = "venv"

[train_and_eval]
pipeline = ["train", "eval"]

[train_and_eval.train.environment]
foo = "bat"

[train_and_eval.eval.options]
foo = "lol"
