default_job = "clean"

[build]
command = "python3 setup.py sdist >/dev/null 2>&1"

[upload]
command = "twine upload dist/*"

[clean]
command = "rm -f dist/*"

[commit]
command = 'git add setup.py && git commit -am "Version bump ($(grep version setup.py | cut -f 2 -d\"))"'

[tag]
command = 'git tag $(grep version setup.py | cut -f 2 -d\")'

[push]
command = 'git push --follow-tags'

[publish]
pipeline = ["_versionbump", "commit", "tag", "push", "build", "upload", "clean"]
aliases = ["p"]
